/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: "Hello World",
		description: "Hello World Template",
		sources: [{
			location: "/template-hello-world/service.mjs.template",
			action: "copy",
			rename: "{{fileName}}.mjs"
		}],
		parameters: [],
		order: -1
	};
};
