/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	var sources = [];
	if (parameters && parameters.includeLaunchpad) {
		sources = [{
			location: "/template-application-ui-angular/index.html.template",
			action: "generate",
			rename: "gen/index.html",
		}, {
			location: "/template-application-ui-angular/ui/resources/templates/menu.html.template",
			action: "generate",
			start: "[[",
			end: "]]",
			rename: "gen/ui/resources/templates/menu.html"
		}, {
			location: "/template-application-ui-angular/ui/resources/templates/sidebar.html.template",
			action: "copy",
			rename: "gen/ui/resources/templates/sidebar.html"
		}, {
			location: "/template-application-ui-angular/ui/resources/templates/tiles.html.template",
			action: "copy",
			rename: "gen/ui/resources/templates/tiles.html"
		}, {
			location: "/template-application-ui-angular/ui/resources/js/message-hub.js.template",
			action: "copy",
			rename: "gen/ui/resources/js/message-hub.js"
		}, {
			location: "/template-application-ui-angular/ui/resources/js/ui-bootstrap-tpls-0.14.3.min.js.template",
			action: "copy",
			rename: "gen/ui/resources/js/ui-bootstrap-tpls-0.14.3.min.js"
		}, {
			location: "/template-application-ui-angular/ui/resources/js/ui-core-ng-modules.js.template",
			action: "generate",
			rename: "gen/ui/resources/js/ui-core-ng-modules.js"
		}, {
			location: "/template-application-ui-angular/ui/resources/js/ui-layout.js.template",
			action: "generate",
			rename: "gen/ui/resources/js/ui-layout.js"
		}, {
			location: "/template-application-ui-angular/ui/extensions/perspective.extensionpoint.template",
			action: "generate",
			rename: "gen/ui/extensions/perspective.extensionpoint"
		}, {
			location: "/template-application-ui-angular/ui/extensions/perspective.extension.template",
			action: "generate",
			rename: "gen/ui/extensions/perspective.extension"
		}, {
			location: "/template-application-ui-angular/ui/extensions/perspective.js.template",
			action: "generate",
			rename: "gen/ui/extensions/perspective.js"
		}, {
			location: "/template-application-ui-angular/ui/extensions/tiles.extensionpoint.template",
			action: "generate",
			rename: "gen/ui/extensions/tiles.extensionpoint"
		}];
	}
	return sources;
};
