/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	return [{
		location: "/template-application-ui-angular/ui/extensions/menu.extensionpoint.template",
		action: "generate",
		rename: "gen/ui/extensions/menu.extensionpoint"
	}];
};
