/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	return [{
		location: "/template-application-ui-angular/ui/perspectives/extensions/tile/tile.extension.template",
		action: "generate",
		rename: "gen/ui/{{perspectiveName}}/views/{{name}}/extensions/tile/tile.extension",
		collection: "uiPrimaryModels"
	}, {
		location: "/template-application-ui-angular/ui/perspectives/extensions/tile/tile.extension.template",
		action: "generate",
		rename: "gen/ui/{{perspectiveName}}/views/{{name}}/extensions/tile/tile.extension",
		collection: "uiReportModels"
	}, {
		location: "/template-application-ui-angular/ui/perspectives/extensions/tile/tile.js.template",
		action: "generate",
		rename: "gen/ui/{{perspectiveName}}/views/{{name}}/extensions/tile/tile.js",
		engine: "velocity",
		collection: "uiPrimaryModels"
	}, {
		location: "/template-application-ui-angular/ui/perspectives/extensions/tile/tile.js.template",
		action: "generate",
		rename: "gen/ui/{{perspectiveName}}/views/{{name}}/extensions/tile/tile.js",
		engine: "velocity",
		collection: "uiReportModels"
	}];
};
