/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: 'React (UI)',
		description: 'React Template',
		image: '/services/web/template-react/template.svg',
		sources: [{
			location: '/template-react/index.tsx.template',
			action: 'generate',
			rename: 'index.tsx'
		}, {
			location: '/template-react/index.html.template',
			action: 'generate',
			rename: 'index.html'
		}, {
			location: '/template-react/.gitignore.template',
			action: 'generate',
			rename: '.gitignore'
		}, {
			location: '/template-react/project.json.template',
			action: 'generate',
			rename: 'project.json'
		}, {
			location: '/template-react/app.tsx.template',
			action: 'generate',
			rename: '{{fileName}}.tsx'
		}],
		parameters: [],
		order: 35
	};
};
