/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "ide-generate-service/template/generateUtils";
import * as parameterUtils from "ide-generate-service/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    return {
        name: "Application - Schema",
        description: "Application with a Database Schema",
        extension: "model",
        sources: [{
            location: "/template-application-schema/data/application.schema.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/schema/{{projectName}}.schema",
            engine: "velocity"
        }],
        parameters: [{
            name: "tablePrefix",
            label: "Table Prefix",
            placeholder: "Table prefix",
            required: false
        }, {
            name: "dataSource",
            label: "Data Source",
            placeholder: "Data Source (DefaultDB)",
            required: false
        }]
    };
};