SELECT MSGOUT_ID, MSG_ID, MSG_CREATED_BY, MSG_CREATED_AT, MSG_SUBJECT, MSG_BODY, MSGCLIENT_NAME
FROM DGB_MSG_OUT, DGB_MSG_MESSAGES, DGB_MSG_CLIENTS, DGB_MSG_IN
WHERE MSGOUT_RECEIVER = ? AND MSG_MSGTOPIC_ID = ? AND MSGOUT_MSG_ID = MSG_ID AND MSGIN_SENDER = MSGCLIENT_ID AND MSGIN_MSG_ID = MSG_ID AND MSGOUT_STATUS = 0