/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
	return {
		name: "Extension (View)",
		description: "Generates a basic view",
		sources: [{
			location: "/template-extension-view/views/view/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "index.html"
		}, {
			location: "/template-extension-view/views/view/controller.js.template",
			action: "generate",
			rename: "js/{{fileName}}.js"
		}, {
			location: "/template-extension-view/views/view/view.js.template",
			action: "generate",
			rename: "services/{{fileName}}-view.js"
		}, {
			location: "/template-extension-view/extensions/views/view.extension.template",
			action: "generate",
			rename: "extensions/{{fileName}}.extension"
		}],
		parameters: [{
			name: "viewName",
			label: "Name"
		}]
	};
};
