/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const perspectiveData = {
	id: "{{perspectiveName}}",
	name: "{{perspectiveName}}",
	link: "/services/v4/web/{{projectName}}/gen/ui/{{perspectiveName}}/index.html",
	order: "{{perspectiveOrder}}",
	icon: "{{perspectiveIcon}}",
};

if (typeof exports !== 'undefined') {
	exports.getPerspective = function () {
		return perspectiveData;
	}
}