/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
    id: "{{name}}-details",
    label: "{{name}}",
    factory: "frame",
    region: "center",
    link: "/services/web/{{projectName}}/gen/ui/{{perspectiveName}}/{{name}}/main-details/index.html",
    perspectiveName: "{{perspectiveName}}"
};

if (typeof exports !== 'undefined') {
    exports.getView = function () {
        return viewData;
    }
}
