/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as daoTemplateManager from "template-application-dao/template/template";
import * as generateUtils from "ide-generate-service/template/generateUtils";
import * as parameterUtils from "ide-generate-service/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    let daoTemplate = daoTemplateManager.getTemplate(parameters);

    let templateSources = [{
        location: "/template-application-feed/feed/entityFeedSynchronizer.js.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/feed/{{perspectiveName}}/{{name}}FeedSynchronizer.js",
        engine: "velocity",
        collection: "feedModels"
    }, {
        location: "/template-application-feed/feed/entityFeed.job.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/feed/{{perspectiveName}}/{{name}}Feed.job",
        engine: "velocity",
        collection: "feedModels"
    }];
    templateSources = templateSources.concat(daoTemplate.sources);

    let templateParameters = [];
    templateParameters = templateParameters.concat(daoTemplate.parameters);

    return {
        name: "Application - Feed",
        description: "Application with Feed Entities",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};