/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
    return {
        name: "OpenUI5 - Table",
        description: "OpenUI5 Template - Table",
        sources: [
            {
                location: "/template-openui5-table/ui/Component.js",
                rename: "/Component.js",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/index.html",
                rename: "/index.html",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/manifest.json",
                rename: "/manifest.json",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/controller/Formatter.js",
                rename: "/controller/Formatter.js",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/controller/SettingsDialogController.controller.js",
                rename: "/controller/SettingsDialogController.controller.js",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/mockdata/products.json",
                rename: "/mockdata/products.json",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/view/FilterDialog.fragment.xml",
                rename: "/view/FilterDialog.fragment.xml",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/view/GroupDialog.fragment.xml",
                rename: "/view/GroupDialog.fragment.xml",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/view/SettingsDialogView.view.xml",
                rename: "/view/SettingsDialogView.view.xml",
                action: "copy"
            },
            {
                location: "/template-openui5-table/ui/view/SortDialog.fragment.xml",
                rename: "/view/SortDialog.fragment.xml",
                action: "copy"
            }
        ],
        parameters: []
    };
};