/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
(function() {
    var generator = dirigibleRequire("template-form-builder-angularjs/template/generate-form-angularjs");
    return generator.generateView(__context.get('workspaceName'), __context.get('projectName'), __context.get('filePath'));
})();