/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
	id: "example-widgets",
	label: "Widgets Examples",
	factory: "frame",
	region: "bottom",
	link: "index.html",
};
if (typeof exports !== 'undefined') {
	exports.getView = function () {
		return viewData;
	}
}