/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
    return {
        name: "OpenUI5 - Tiles",
        description: "OpenUI5 Template - Tiles",
        sources: [
            {
                location: "/template-openui5-tiles/ui/Component.js",
                rename: "/Component.js",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/index.html",
                rename: "/index.html",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/manifest.json",
                rename: "/manifest.json",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/tiles.json",
                rename: "/tiles.json",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/controller/Page.controller.js",
                rename: "/controller/Page.controller.js",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/css/style.css",
                rename: "/css/style.css",
                action: "copy"
            },
            {
                location: "/template-openui5-tiles/ui/view/Page.view.xml",
                rename: "/view/Page.view.xml",
                action: "copy"
            }
        ],
        parameters: []
    };
};