/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const generateUtils = require("ide-generate-service/template/generateUtils");
const parameterUtils = require("ide-generate-service/template/parameterUtils");

exports.generate = function (model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = exports.getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

exports.getTemplate = function (parameters) {

    return {
        name: "Application - OData",
        description: "Application with a OData",
        extension: "model",
        sources: [{
            location: "/template-application-odata/odata/application.odata.template",
            action: "generate",
            rename: "gen/odata/{{projectName}}.odata",
            engine: "velocity"
        }],
        parameters: [{
            name: "tablePrefix",
            label: "Table Prefix",
            placeholder: "Table prefix"
        }, {
            name: "odataNamespace",
            label: "Namespace",
            placeholder: "Namespace for OData API"
        }]
    };
};