/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "Scheduled Job",
		"description": "Scheduled Job definition with a simple Javascript handler",
		"sources": [
		{
			"location": "/template-job/job.template", 
			"action": "generate",
			"rename": "{{fileName}}.job"
		},
		{
			"location": "/template-job/handler.js.template", 
			"action": "generate",
			"rename": "{{fileName}}-handler.js"
		}],
		"parameters": []
	};
};
