/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: "Scheduled Job (Model)",
		description: "Scheduled Job definition with a simple Javascript handler",
		sources: [{
			location: "/template-job/job.template",
			action: "generate",
			rename: "{{fileName}}.job"
		}, {
			location: "/template-job/handler.js.template",
			action: "generate",
			rename: "{{fileName}}-handler.js"
		}],
		parameters: [],
		order: 50
	};
};
