{{- if eq .Values.keycloak.enabled false }}
{{- if .Values.kyma.enabled }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-{{ include "dirigible.fullname" . }}
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServiceClassRef:
    name: xsuaa
  clusterServicePlanExternalName: broker
  externalID: {{ uuidv4 }}
  parameters:
    xsappname: {{ include "dirigible.fullname" . }}-xsuaa
    oauth2-configuration:
      redirect-uris:
      - https://{{ .Release.Name }}.{{ .Values.kyma.apirule.host }}
      token-validity: 7200
    role-collections:
    - description: Dirigible Developer
      name: {{ include "dirigible.fullname" . }}
      role-template-references:
      - $XSAPPNAME.Developer
      - $XSAPPNAME.Operator
    role-templates:
    - description: Developer related roles
      name: Developer
      scope-references:
      - $XSAPPNAME.Developer
    - description: Operator related roles
      name: Operator
      scope-references:
      - $XSAPPNAME.Operator
    scopes:
    - description: Developer scope
      name: $XSAPPNAME.Developer
    - description: Operator scope
      name: $XSAPPNAME.Operator

---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-{{ include "dirigible.fullname" . }}-binding
spec:
  externalID: {{ uuidv4 }}
  instanceRef:
    name: xsuaa-{{ include "dirigible.fullname" . }}
  parameters: {}
  secretName: xsuaa-{{ include "dirigible.fullname" . }}-binding

---

apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-{{ include "dirigible.fullname" . }}-usage
spec:
  parameters:
    envPrefix:
      name: ""
  serviceBindingRef:
    name: xsuaa-{{ include "dirigible.fullname" . }}-binding
  usedBy:
    kind: deployment
    name: {{ include "dirigible.fullname" . }}
{{- end }}
{{- end }}