INSERT INTO DGB_ACCESS_LOG (
ACCLOG_REQUEST_URI,
ACCLOG_REMOTE_USER,
ACCLOG_REMOTE_HOST,
ACCLOG_SESSION_ID,
ACCLOG_METHOD,
ACCLOG_USER_AGENT,
ACCLOG_RESPONSE_STATUS, 
ACCLOG_TIMESTAMP,
ACCLOG_PERIOD,
ACCLOG_PATTERN,
ACCLOG_PROJECT,
ACCLOG_RESPONSE_TIME) 
VALUES (?,?,?,?,?,?,?,?,?,?,?,?)