/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "HTTP Client",
		"description": "HTTP Client Template",
		"sources": [{
			"location": "/template-http-client/service.mjs.template", 
			"action": "generate",
			"rename": "{{fileName}}.mjs"
		}],
		"parameters": [],
		"order": 20
	};
};
