/*
 * Copyright (c) 2022 SAP SE or an SAP affiliate company and Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTile = function () {
    return {
        group: "{{perspectiveName}}",
        name: "{{name}}",
        caption: "{{caption}}",
        tooltip: "{{tooltip}}",
        // icon: "file-o",
        location: "/services/v4/web/{{projectName}}/gen/ui/{{perspectiveName}}/index.html",
        order: "{{menuIndex}}",
        groupOrder: "{{perspectiveOrder}}"
    };
};
