/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
    var sources = [];
    if (parameters && parameters.includeLaunchpad) {
        sources = [{
            location: "/template-application-ui-angular/shell/launchpad/menu.js.template",
            action: "generate",
            rename: "gen/shell/launchpad/menu.js"
        }, {
            location: "/template-application-ui-angular/shell/launchpad/perspectives.js.template",
            action: "generate",
            rename: "gen/shell/launchpad/perspectives.js"
        }, {
            location: "/template-application-ui-angular/shell/launchpad/tiles.js.template",
            action: "generate",
            rename: "gen/shell/launchpad/tiles.js"
        }, {
            location: "/template-application-ui-angular/shell/launchpad/views.js.template",
            action: "generate",
            rename: "gen/shell/launchpad/views.js"
        }];
    }
    return sources;
};
