/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: 'View with HTTP data requests (UI)',
		description: 'Dirigible view with tables and HTTP data requests.',
		sources: [{
			location: '/template-html/index.html.template',
			action: 'generate',
			rename: '{{fileName}}.html',
			start: '[[',
			end: ']]'
		}],
		parameters: [],
		order: 30
	};
};
