/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: "AngularJS (UI)",
		description: "HTML5 Template with AngularJS",
		sources: [{
			location: "/template-html/index.html.template", 
			action: "generate",
			rename: "{{fileName}}.html",
			start : "[[",
			end : "]]"
		}],
		parameters: [],
		order: 30
	};
};
