exports.getFileTypes = function () {
    return {
        ".abap": "abap",
        ".js": "javascript",
        ".mjs": "javascript",
        ".ts": "typescript",
        ".html": "html",
        ".css": "css",
        ".json": "json",
        ".table": "json",
        ".view": "json",
        ".extensionpoint": "json",
        ".extension": "json",
        ".job": "json",
        ".xsjob": "json",
        ".listener": "json",
        ".access": "json",
        ".roles": "json",
        ".command": "json",
        ".xml": "xml",
        ".bpmn": "xml",
        ".model": "json",
        ".edm": "xml",
        ".schema": "json",
        ".odata": "json",
        ".sql": "sql",
        ".md": "markdown",
        ".yml": "yaml",
        ".yaml": "yaml",
        ".openapi": "yaml",
        ".py": "python"
    }
};