DELETE FROM DGB_SCHEMA_VERSIONS;
INSERT INTO DGB_SCHEMA_VERSIONS (
	SCHV_VERSION, SCHV_DESCRIPTION)
	VALUES (3, 'Free Text Search in Documents');

CREATE INDEX DGB_DOCUMENTS_DOC_CONTENT_IDX ON DGB_DOCUMENTS (DOC_CONTENT);

