/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as schemaTemplateManager from "template-application-schema/template/template";
import * as feedTemplateManager from "template-application-feed/template/template";
import * as uiAngularjsTemplateManager from "template-application-ui-angular/template/template";
import * as odataTemplateManager from "template-application-odata/template/template";
import * as generateUtils from "ide-generate-service/template/generateUtils";
import * as parameterUtils from "ide-generate-service/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters);
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    let schemaTemplate = schemaTemplateManager.getTemplate(parameters);
    let feedTemplate = feedTemplateManager.getTemplate(parameters);
    let uiAngularjsTemplate = uiAngularjsTemplateManager.getTemplate(parameters);
    let odataTemplate = odataTemplateManager.getTemplate(parameters);

    let templateSources = [];
    templateSources = templateSources.concat(schemaTemplate.sources);
    templateSources = templateSources.concat(feedTemplate.sources);
    templateSources = templateSources.concat(uiAngularjsTemplate.sources);
    templateSources = templateSources.concat(odataTemplate.sources);

    odataTemplate.parameters.push({
        name: "generateOData",
        label: "OData",
        type: "checkbox"
    });
    odataTemplate.parameters.forEach(e => {
        if (e.name === "odataNamespace") {
            e.ui = {
                hide: {
                    property: "generateOData",
                    value: false
                }
            };
        }
    });

    return {
        name: "Application - Full Stack",
        description: "Application - full stack with a Database Schema, a set of REST Services and an AngularJS User Interfaces",
        extension: "model",
        sources: templateSources,
        parameters: parameterUtils.getUniqueParameters(schemaTemplate.parameters, feedTemplate.parameters, uiAngularjsTemplate.parameters, odataTemplate.parameters)
    };
};
