/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const perspectiveData = {
	id: "home",
	name: "Home",
	link: "/services/web/${projectName}/gen/index.html",
	order: "1",
	icon: "/services/web/resources/unicons/estate.svg",
};

if (typeof exports !== 'undefined') {
	exports.getPerspective = function () {
		return perspectiveData;
	}
}