/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
    id: "{{name}}-details-filter",
    label: "{{name}}",
    link: "/services/web/{{projectName}}/gen/ui/{{perspectiveName}}/{{name}}/dialog-window-filter/index.html",
    perspectiveName: "{{perspectiveName}}"
};

if (typeof exports !== 'undefined') {
    exports.getDialogWindow = function () {
        return viewData;
    }
}