/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const restTemplateManager = dirigibleRequire("template-application-rest/template/template");
const uiTemplate = dirigibleRequire("template-application-ui-angular/template/ui/template");
const generateUtils = dirigibleRequire("ide-generate-service/template/generateUtils");
const parameterUtils = dirigibleRequire("ide-generate-service/template/parameterUtils");

exports.generate = function (model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = exports.getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    templateSources = [];
    return generateUtils.generateFiles(model, parameters, templateSources);
};

exports.getTemplate = function (parameters) {
    let restTemplate = restTemplateManager.getTemplate(parameters);

    let templateSources = [];
    templateSources = templateSources.concat(restTemplate.sources);
    templateSources = templateSources.concat(uiTemplate.getSources(parameters));

    let templateParameters = getTemplateParameters();
    templateParameters = templateParameters.concat(restTemplate.parameters);

    return {
        name: "Application - UI (AngularJS)",
        description: "Application with UI, REST APIs and DAOs",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};

function getTemplateParameters() {
    return [
        {
            name: "brand",
            label: "Brand",
            placeholder: "Enter Brand"
        },
        {
            name: "brandUrl",
            label: "Brand URL",
            placeholder: "Enter Brand URL"
        },
        {
            name: "title",
            label: "Title",
            placeholder: "Enter Title"
        },
        {
            name: "description",
            label: "Description",
            placeholder: "Enter Description"
        }
    ];
}