/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
	return {
		name: "Extension (Perspective)",
		description: "Generates a basic perspective",
		sources: [{
			location: "/template-extension-perspective/extensions/menu/help.extension.template",
			action: "generate",
			rename: "/extensions/menu/help.extension"
		}, {
			location: "/template-extension-perspective/extensions/menu/window.extension.template",
			action: "generate",
			rename: "/extensions/menu/window.extension"
		}, {
			location: "/template-extension-perspective/extensions/menu/perspective-menu.extension.template",
			action: "generate",
			rename: "/extensions/menu/{{fileName}}.extension"
		}, {
			location: "/template-extension-perspective/extensions/menu/perspective-menu.extensionpoint.template",
			action: "generate",
			rename: "/extensions/menu/{{fileName}}-menu.extensionpoint"
		}, {
			location: "/template-extension-perspective/extensions/perspective.extension.template",
			action: "generate",
			rename: "/extensions/perspective.extension"
		}, {
			location: "/template-extension-perspective/index.html.template",
			action: "generate",
			rename: "index.html"
		}, {
			location: "/template-extension-perspective/js/perspective.js.template",
			action: "generate",
			rename: "js/perspective.js"
		}, {
			location: "/template-extension-perspective/services/menu/perspective.js.template",
			action: "generate",
			rename: "/services/menu/{{fileName}}.js"
		}, {
			location: "/template-extension-perspective/services/perspective.js.template",
			action: "generate",
			rename: "/services/{{fileName}}.js"
		}, {
			location: "/template-extension-perspective/images/perspective.svg.template",
			action: "generate",
			rename: "/images/perspective.svg"
		}],
		parameters: []
	};
};
