# Docker descriptor for Dirigible
# License - http://www.eclipse.org/legal/epl-v20.html
 
FROM tomcat:9.0.56-jre11-openjdk
 
COPY server-all/target/ROOT.war $CATALINA_HOME/webapps/

RUN rm /usr/local/tomcat/conf/tomcat-users.xml
RUN wget https://www.dirigible.io/help/conf/tomcat-users.xml -P /usr/local/tomcat/conf/ --no-check-certificate

RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.4.1/postgresql-42.4.1.jar -P /usr/local/tomcat/lib/
RUN wget https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.8.12/ngdbc-2.8.12.jar -P /usr/local/tomcat/lib/

ENV DIRIGIBLE_JAVASCRIPT_GRAALVM_DEBUGGER_PORT=0.0.0.0:8081

EXPOSE 8080 8081

CMD ["catalina.sh", "jpda", "run"]
