/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "Database Table",
		"description": "Database Table Template",
		"sources": [{
			"location": "/template-database-table/database.table.template", 
			"action": "generate",
			"rename": "{{fileName}}.table"
		}],
		"parameters": [{
			"name": "tableName",
			"label": "Table Name"
		}],
		"order": 10
	};
};
