/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function() {
	return {
		"name": "Extension (View)",
		"description": "Extension view for the IDE",
		"sources": [{
			"location": "/template-extension-view/views/view/index.html.template", 
			"action": "copy",
			"rename": "views/{{fileName}}/index.html"
		}, {
			"location": "/template-extension-view/views/view/controller.js.template", 
			"action": "generate",
			"rename": "views/{{fileName}}/controller.js"
		}, {
			"location": "/template-extension-view/views/view/view.js.template", 
			"action": "generate",
			"rename": "views/{{fileName}}/view.js"
		}, {
			"location": "/template-extension-view/extensions/views/view.extension.template", 
			"action": "generate",
			"rename": "extensions/views/{{fileName}}.extension"
		}],
		"parameters": [{
			"name": "viewName",
			"label": "Name"
		}]
	};
};
