/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const perspectiveData = {
	id: 'home',
	name: 'Home',
	link: '/services/web/portal/index.html',
	icon: '/services/web/resources/unicons/estate.svg',
	order: 1,
};

if (typeof exports !== 'undefined') {
	exports.getPerspective = function () {
		return perspectiveData;
	}
}