/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
angular.module('page', ["ideUI", "ideView", "entityApi"])
    .config(["messageHubProvider", function (messageHubProvider) {
        messageHubProvider.eventIdPrefix = 'test.entities.Student';
    }])
    .controller('PageController', ['$scope', 'ViewParameters', function ($scope, ViewParameters) {

        $scope.src = ViewParameters.get().src;

    }]);