/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
    id: "{{projectName}}-custom-action",
    label: "Custom Action",
    link: "/services/web/{{projectName}}/gen/ui/custom-action-dialog/index.html"
};

if (typeof exports !== 'undefined') {
    exports.getDialogWindow = function () {
        return viewData;
    }
}