/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
	return {
		"name": "Form",
		"description": "TypeScript Sample Template",
		"sources": [{
			"location": "/template-form/project.json.template",
			"action": "generate",
			"rename": "project.json"
		}, {
			"location": "/template-form/tsconfig.json.template",
			"action": "copy",
			"rename": "tsconfig.json"
		}, {
			"location": "/template-form/service.ts.template",
			"action": "copy",
			"rename": "{{fileName}}.ts"
		}],
		"parameters": [],
		"order": 1
	};
};
