/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getTemplate = function () {
    return {
        name: "OpenUI5 - Wizard",
        description: "OpenUI5 Template - Wizard",
        sources: [
            {
                location: "/template-openui5-wizard/ui/Component.js",
                rename: "/Component.js",
                action: "copy"
            },
            {
                location: "/template-openui5-wizard/ui/index.html",
                rename: "/index.html",
                action: "copy"
            },
            {
                location: "/template-openui5-wizard/ui/manifest.json",
                rename: "/manifest.json",
                action: "copy"
            },
            {
                location: "/template-openui5-wizard/ui/controller/Wizard.controller.js",
                rename: "/controller/Wizard.controller.js",
                action: "copy"
            },
            {
                location: "/template-openui5-wizard/ui/view/ReviewPage.fragment.xml",
                rename: "/view/ReviewPage.fragment.xml",
                action: "copy"
            },
            {
                location: "/template-openui5-wizard/ui/view/Wizard.view.xml",
                rename: "/view/Wizard.view.xml",
                action: "copy"
            }
        ],
        parameters: []
    };
};