/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	return [
		// Location: "gen/ui/custom-action-dialog"
		{
			location: "/template-application-ui-angular/ui/custom-action-dialog/controller.js",
			action: "copy",
			rename: "gen/ui/custom-action-dialog/controller.js"
		},
		{
			location: "/template-application-ui-angular/ui/custom-action-dialog/custom-action.extensionpoint",
			action: "generate",
			rename: "gen/ui/custom-action-dialog/custom-action.extensionpoint"
		},
		{
			location: "/template-application-ui-angular/ui/custom-action-dialog/index.html",
			action: "copy",
			rename: "gen/ui/custom-action-dialog/index.html"
		},
		{
			location: "/template-application-ui-angular/ui/custom-action-dialog/view.extension",
			action: "generate",
			rename: "gen/ui/custom-action-dialog/view.extension"
		}, {
			location: "/template-application-ui-angular/ui/custom-action-dialog/view.js",
			action: "generate",
			rename: "gen/ui/custom-action-dialog/view.js"
		}];
};
