/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	return [
		// Location: "gen/ui/perspective"
		{
			location: "/template-application-ui-angular/ui/perspective/index.html",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/index.html",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/perspective.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective-portal.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/perspective-portal.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/perspective.js",
			collection: "uiReportChartModels"
		},
		// Location: "gen/ui/perspective/list"
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/dialog-window-filter/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/dialog-window-filter/controller.js",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/dialog-window-filter/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/dialog-window-filter/index.html",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/dialog-window-filter/view.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/dialog-window-filter/view.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/dialog-window-filter/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/dialog-window-filter/view.js",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/controller.js",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/index.html",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/tile.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/tile.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/tile-portal.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/tile-portal.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/tile.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/tile.js",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/view.extension",
			action: "generate",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/view.extension",
			collection: "uiReportChartModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report-chart/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/{{perspectiveName}}/{{name}}/view.js",
			collection: "uiReportChartModels"
		}];
};