/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
	return [
		// Location: "gen/ui/perspective"
		{
			location: "/template-application-ui-angular/ui/perspective/index-report.html",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective-report.extension",
			action: "generate",
			rename: "gen/ui/Reports/perspective.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective-portal-report.extension",
			action: "generate",
			rename: "gen/ui/Reports/perspective-portal.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/perspective-report.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/perspective.js",
			collection: "generateReportModels"
		},
		// Location: "gen/ui/perspective/list"
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-window/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-window/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-window/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-window/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-window/view.extension",
			action: "generate",
			rename: "gen/ui/Reports/{{name}}/dialog-window/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-window/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-window/view.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-filter/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-filter/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-filter/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-filter/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-filter/view.extension",
			action: "generate",
			rename: "gen/ui/Reports/{{name}}/dialog-filter/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/dialog-filter/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/dialog-filter/view.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/tile.extension",
			action: "generate",
			rename: "gen/ui/Reports/{{name}}/tile.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/tile-portal.extension",
			action: "generate",
			rename: "gen/ui/Reports/{{name}}/tile-portal.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/tile.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/tile.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/view.extension",
			action: "generate",
			rename: "gen/ui/Reports/{{name}}/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular/ui/perspective/report/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/ui/Reports/{{name}}/view.js",
			collection: "generateReportModels"
		}];
};
