/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
exports.getSources = function (parameters) {
    return [
        // Location: "gen/ui/perspective"
        {
            location: "/template-application-ui-angular/ui/perspective/index-report.html",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/perspective-report.extension",
            action: "generate",
            rename: "gen/ui/Reports/perspective.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/perspective-portal-report.extension",
            action: "generate",
            rename: "gen/ui/Reports/perspective-portal.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/perspective-report.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/perspective.js",
            collection: "generateReportModels"
        },
        // Location: "gen/ui/perspective/list"
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-window/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-window/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/view.extension",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/dialog-window/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-window/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-filter/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-filter/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/view.extension",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/dialog-filter/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-filter/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/tile.extension",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/tile.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/tile-portal.extension",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/tile-portal.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/tile.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/tile.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/view.extension",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-print/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/ui/Reports/{{name}}/dialog-print/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/print.extension.template",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/dialog-print/print.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/print.js.template",
            action: "generate",
            rename: "gen/ui/Reports/{{name}}/dialog-print/print.js",
            collection: "generateReportModels"
        }];
};
