/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const daoTemplateManager = dirigibleRequire("template-application-dao/template/template");
const generateUtils = dirigibleRequire("ide-generate-service/template/generateUtils");
const parameterUtils = dirigibleRequire("ide-generate-service/template/parameterUtils");

exports.generate = function (model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = exports.getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

exports.getTemplate = function (parameters) {
    let daoTemplate = daoTemplateManager.getTemplate(parameters);

    let templateSources = [{
        location: "/template-application-feed/feed/entityFeedSynchronizer.js.template",
        action: "generate",
        rename: "gen/feed/{{perspectiveName}}/{{name}}FeedSynchronizer.js",
        engine: "velocity",
        collection: "feedModels"
    }, {
        location: "/template-application-feed/feed/entityFeed.job.template",
        action: "generate",
        rename: "gen/feed/{{perspectiveName}}/{{name}}Feed.job",
        engine: "velocity",
        collection: "feedModels"
    }];
    templateSources = templateSources.concat(daoTemplate.sources);

    let templateParameters = [];
    templateParameters = templateParameters.concat(daoTemplate.parameters);

    return {
        name: "Application - Feed",
        description: "Application with Feed Entities",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};